services:
  postgres:
    image: postgres:16
    container_name: lectrium_test
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./Lectrium
    container_name: lectrium_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://lectrium_test:5432/test
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    ports:
      - "8080:8080"

volumes:
  postgres_data: